version: '3.7'

services:

  postgres:
    restart: always
    image: postgres:11.4
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASS
      POSTGRES_DB: $DB_NAME
    ports:
      - "6432:5432"
