# Generated by Django 3.1.3 on 2020-11-12 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=60)),
                ('city', models.CharField(max_length=60)),
                ('post_code', models.IntegerField(default='11111')),
            ],
            options={
                'verbose_name_plural': 'Adresy',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Software', 'SOFTWARE'), ('Fintech', 'FINTECH'), ('Outsourcing', 'OUTSOURCING')], max_length=100, verbose_name='Nazwa kategorii')),
            ],
            options={
                'verbose_name_plural': 'Kategorie',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Nazwa')),
                ('registration_date', models.DateField(verbose_name='Rejestracja')),
                ('owner', models.CharField(max_length=60, verbose_name='Właściciel')),
                ('description', models.TextField(verbose_name='Opis')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('phone_number', models.CharField(max_length=60, verbose_name='Telefon')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktywna')),
                ('address', models.ManyToManyField(to='company.Address', verbose_name='Adres')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.category', verbose_name='Kategoria')),
            ],
            options={
                'verbose_name_plural': 'Firmy',
            },
        ),
    ]
